<?php

namespace App\Helpers;

class QuranHelper
{
    public static function getSurahs(): array
    {
        return [
            "Al-Fatihah" => ["juz" => 1, "ayat" => 7],
            "Al-Baqarah" => ["juz" => 1, "ayat" => 286],
            "Ali 'Imran" => ["juz" => 3, "ayat" => 200],
            "An-Nisa'" => ["juz" => 4, "ayat" => 176],
            "Al-Ma'idah" => ["juz" => 6, "ayat" => 120],
            "Al-An'am" => ["juz" => 7, "ayat" => 165],
            "Al-A'raf" => ["juz" => 8, "ayat" => 206],
            "Al-Anfal" => ["juz" => 9, "ayat" => 75],
            "At-Tawbah" => ["juz" => 10, "ayat" => 129],
            "Yunus" => ["juz" => 11, "ayat" => 109],
            "Hud" => ["juz" => 11, "ayat" => 123],
            "Yusuf" => ["juz" => 12, "ayat" => 111],
            "Ar-Ra'd" => ["juz" => 13, "ayat" => 43],
            "Ibrahim" => ["juz" => 13, "ayat" => 52],
            "Al-Hijr" => ["juz" => 14, "ayat" => 99],
            "An-Nahl" => ["juz" => 14, "ayat" => 128],
            "Al-Isra'" => ["juz" => 15, "ayat" => 111],
            "Al-Kahf" => ["juz" => 15, "ayat" => 110],
            "Maryam" => ["juz" => 16, "ayat" => 98],
            "Taha" => ["juz" => 16, "ayat" => 135],
            "Al-Anbiya'" => ["juz" => 17, "ayat" => 112],
            "Al-Hajj" => ["juz" => 17, "ayat" => 78],
            "Al-Mu'minun" => ["juz" => 18, "ayat" => 118],
            "An-Nur" => ["juz" => 18, "ayat" => 64],
            "Al-Furqan" => ["juz" => 18, "ayat" => 77],
            "Asy-Syu'ara'" => ["juz" => 19, "ayat" => 227],
            "An-Naml" => ["juz" => 19, "ayat" => 93],
            "Al-Qasas" => ["juz" => 20, "ayat" => 88],
            "Al-'Ankabut" => ["juz" => 20, "ayat" => 69],
            "Ar-Rum" => ["juz" => 21, "ayat" => 60],
            "Luqman" => ["juz" => 21, "ayat" => 34],
            "As-Sajdah" => ["juz" => 21, "ayat" => 30],
            "Al-Ahzab" => ["juz" => 21, "ayat" => 73],
            "Saba'" => ["juz" => 22, "ayat" => 54],
            "Fatir" => ["juz" => 22, "ayat" => 45],
            "Yasin" => ["juz" => 22, "ayat" => 83],
            "As-Saffat" => ["juz" => 23, "ayat" => 182],
            "Sad" => ["juz" => 23, "ayat" => 88],
            "Az-Zumar" => ["juz" => 23, "ayat" => 75],
            "Ghafir" => ["juz" => 24, "ayat" => 85],
            "Fussilat" => ["juz" => 24, "ayat" => 54],
            "Asy-Syura" => ["juz" => 25, "ayat" => 53],
            "Az-Zukhruf" => ["juz" => 25, "ayat" => 89],
            "Ad-Dukhan" => ["juz" => 25, "ayat" => 59],
            "Al-Jasiyah" => ["juz" => 25, "ayat" => 37],
            "Al-Ahqaf" => ["juz" => 26, "ayat" => 35],
            "Muhammad" => ["juz" => 26, "ayat" => 38],
            "Al-Fath" => ["juz" => 26, "ayat" => 29],
            "Al-Hujurat" => ["juz" => 26, "ayat" => 18],
            "Qaf" => ["juz" => 26, "ayat" => 45],
            "Az-Zariyat" => ["juz" => 26, "ayat" => 60],
            "At-Tur" => ["juz" => 27, "ayat" => 49],
            "An-Najm" => ["juz" => 27, "ayat" => 62],
            "Al-Qamar" => ["juz" => 27, "ayat" => 55],
            "Ar-Rahman" => ["juz" => 27, "ayat" => 78],
            "Al-Waqi'ah" => ["juz" => 27, "ayat" => 96],
            "Al-Hadid" => ["juz" => 27, "ayat" => 29],
            "Al-Mujadilah" => ["juz" => 28, "ayat" => 22],
            "Al-Hasyr" => ["juz" => 28, "ayat" => 24],
            "Al-Mumtahanah" => ["juz" => 28, "ayat" => 13],
            "As-Saff" => ["juz" => 28, "ayat" => 14],
            "Al-Jumu'ah" => ["juz" => 28, "ayat" => 11],
            "Al-Munafiqun" => ["juz" => 28, "ayat" => 11],
            "At-Taghabun" => ["juz" => 28, "ayat" => 18],
            "At-Talaq" => ["juz" => 28, "ayat" => 12],
            "At-Tahrim" => ["juz" => 28, "ayat" => 12],
            "Al-Mulk" => ["juz" => 29, "ayat" => 30],
            "Al-Qalam" => ["juz" => 29, "ayat" => 52],
            "Al-Haqqah" => ["juz" => 29, "ayat" => 52],
            "Al-Ma'arij" => ["juz" => 29, "ayat" => 44],
            "Nuh" => ["juz" => 29, "ayat" => 28],
            "Al-Jinn" => ["juz" => 29, "ayat" => 28],
            "Al-Muzzammil" => ["juz" => 29, "ayat" => 20],
            "Al-Muddassir" => ["juz" => 29, "ayat" => 56],
            "Al-Qiyamah" => ["juz" => 29, "ayat" => 40],
            "Al-Insan" => ["juz" => 29, "ayat" => 31],
            "Al-Mursalat" => ["juz" => 29, "ayat" => 50],
            "An-Naba'" => ["juz" => 30, "ayat" => 40],
            "An-Nazi'at" => ["juz" => 30, "ayat" => 46],
            "'Abasa" => ["juz" => 30, "ayat" => 42],
            "At-Takwir" => ["juz" => 30, "ayat" => 29],
            "Al-Infitar" => ["juz" => 30, "ayat" => 19],
            "Al-Mutaffifin" => ["juz" => 30, "ayat" => 36],
            "Al-Insyiqaq" => ["juz" => 30, "ayat" => 25],
            "Al-Buruj" => ["juz" => 30, "ayat" => 22],
            "At-Tariq" => ["juz" => 30, "ayat" => 17],
            "Al-A'la" => ["juz" => 30, "ayat" => 19],
            "Al-Ghasyiyah" => ["juz" => 30, "ayat" => 26],
            "Al-Fajr" => ["juz" => 30, "ayat" => 30],
            "Al-Balad" => ["juz" => 30, "ayat" => 20],
            "Asy-Syams" => ["juz" => 30, "ayat" => 15],
            "Al-Layl" => ["juz" => 30, "ayat" => 21],
            "Ad-Duha" => ["juz" => 30, "ayat" => 11],
            "Asy-Syarh" => ["juz" => 30, "ayat" => 8],
            "At-Tin" => ["juz" => 30, "ayat" => 8],
            "Al-'Alaq" => ["juz" => 30, "ayat" => 19],
            "Al-Qadr" => ["juz" => 30, "ayat" => 5],
            "Al-Bayyinah" => ["juz" => 30, "ayat" => 8],
            "Az-Zalzalah" => ["juz" => 30, "ayat" => 8],
            "Al-'Adiyat" => ["juz" => 30, "ayat" => 11],
            "Al-Qari'ah" => ["juz" => 30, "ayat" => 11],
            "At-Takasur" => ["juz" => 30, "ayat" => 8],
            "Al-'Asr" => ["juz" => 30, "ayat" => 3],
            "Al-Humazah" => ["juz" => 30, "ayat" => 9],
            "Al-Fil" => ["juz" => 30, "ayat" => 5],
            "Quraysy" => ["juz" => 30, "ayat" => 4],
            "Al-Ma'un" => ["juz" => 30, "ayat" => 7],
            "Al-Kawsar" => ["juz" => 30, "ayat" => 3],
            "Al-Kafirun" => ["juz" => 30, "ayat" => 6],
            "An-Nasr" => ["juz" => 30, "ayat" => 3],
            "Al-Lahab" => ["juz" => 30, "ayat" => 5],
            "Al-Ikhlas" => ["juz" => 30, "ayat" => 4],
            "Al-Falaq" => ["juz" => 30, "ayat" => 5],
            "An-Nas" => ["juz" => 30, "ayat" => 6],
        ];
    }
}
